name: safechain
description: "SafeChain Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  flutter_map: ^8.2.2
  location: ^8.0.1
  latlong2: ^0.9.1
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  slider_captcha: ^1.0.1
  app_links: ^3.4.1
  flutter_blue_plus: ^1.31.20
  permission_handler: ^11.3.1
  animations: ^2.1.1
  fluttermoji: ^1.0.2
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/